sudo: required
services:
  - docker

before_install:
  - docker build -t siddhi96/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true siddhi96/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-create"
  env: "DockerCreate-env-"
  bucket_name: "elasticbeanstalk-us-west-2-595101688237"
  bucket_path: "docker-create"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

    